#!/usr/bin/env python3
"""
test_gguf_adapters.py  —  Test GGUF adapter mode (shared base + per-player adapter GGUFs).

Generated by convert_adapters_to_gguf.py. Base GGUF is shared; each player adapter
is a small fp16 GGUF (~37 MB) applied at inference time.

Key finding: fp16 base + adapter matches fp16 HuggingFace inference exactly.
Q8_0 base + adapter is close but has residual quantization error on marginal decisions.
Q4_K_M base + adapter raises correctly when loaded in isolation but may check after
accumulated VRAM pressure (llama-cpp-python 0.3.22 broken __del__ leaks CUDA memory).

Storage comparison:
    Merged GGUFs (Q4_K_M):                    7 × ~941 MB  = ~6.5 GB
    Adapter mode (Q4_K_M base + adapters):  ~900 MB + 7 × 37 MB = ~1.2 GB
    Adapter mode (Q8_0  base + adapters):   ~1.6 GB + 7 × 37 MB = ~1.9 GB
    Adapter mode (fp16  base + adapters):   ~2.9 GB + 7 × 37 MB = ~3.2 GB  ← matches HF fp16

Run:
    python tests/test_gguf_adapters.py
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
from action_classes import CLASSES
from game_states import ALL_PLAYERS, PREFLOP_FOLD, FLOP_RAISE

GGUF_ADAPTER_DIR = Path("/data/models/qwen2.5-1.5b-instruct/gguf-adapters")
ADAPTER_SUBDIR   = GGUF_ADAPTER_DIR / "adapters"

_VALID_LABELS  = set(CLASSES)
_RAISE_LABELS  = set(CLASSES[3:])


def is_valid(action: str) -> bool:
    return action.strip() in _VALID_LABELS


def is_raise(action: str) -> bool:
    return action.strip() in _RAISE_LABELS


def test_base(quant: str, failures_ref: list) -> None:
    from llama_cpp import Llama
    from inference_gguf import predict

    base_gguf = GGUF_ADAPTER_DIR / f"base.{quant}.gguf"
    if not base_gguf.exists():
        print(f"  SKIP — base.{quant}.gguf not found")
        return

    size_gb = base_gguf.stat().st_size / 1e9
    adapter_mb = sum(
        (ADAPTER_SUBDIR / f"{p}.gguf").stat().st_size
        for p in ALL_PLAYERS
        if (ADAPTER_SUBDIR / f"{p}.gguf").exists()
    ) / 1e6
    print(f"  Base: {base_gguf.name} ({size_gb:.2f} GB)  "
          f"+ adapters ({adapter_mb:.0f} MB total)")
    print()

    args = argparse.Namespace(
        blinds="$50/$100", stacks="$10,000",
        max_tokens=1, temperature=0.0, top_p=1.0,
        gpu_layers=-1, threads=None, ctx=512, verbose=False,
        lora_scale=1.0,
    )

    states = [
        (PREFLOP_FOLD, "preflop — all should fold", False),
        (FLOP_RAISE,   "flop — all should raise",   True),
    ]

    results: dict[str, dict[str, str]] = {}

    # Load each player once, run all states, then free before the next player.
    # llama-cpp-python 0.3.22 has a broken __del__ that leaks CUDA memory; loading
    # 14 times (2 states × 7 players) exhausts VRAM. 7 loads is safe.
    for player in ALL_PLAYERS:
        lora_path = ADAPTER_SUBDIR / f"{player}.gguf"
        if not lora_path.exists():
            results[player] = {s: f"MISSING ({lora_path.name})" for s, _, _ in states}
            continue

        llm = Llama(
            model_path=str(base_gguf),
            lora_path=str(lora_path),
            lora_scale=1.0,
            n_ctx=512,
            n_gpu_layers=-1,
            verbose=False,
        )
        results[player] = {}
        for state, _, _ in states:
            results[player][state] = predict(llm, player, state, args)
        llm.close()
        del llm

    for state, note, check_raise in states:
        print(f"  ── {note}")
        for player in ALL_PLAYERS:
            action = results[player][state]
            valid  = is_valid(action)
            ok     = action == "fold" if not check_raise else is_raise(action)
            status = "OK" if (valid and ok) else "FAIL"
            if not (valid and ok):
                failures_ref[0] += 1
            print(f"    {status}  {player:<12} → {action}")
        print()


def main() -> None:
    print("=" * 60)
    print("GGUF adapter mode — shared base + per-player adapter GGUFs")
    print("=" * 60)
    print(f"Dir: {GGUF_ADAPTER_DIR}")
    print()

    failures = [0]  # use list so test_base can mutate it

    # fp16 runs first — needs fresh VRAM before prior loads fragment CUDA allocator
    for quant in ["f16", "Q8_0", "Q4_K_M"]:
        print(f"── base.{quant}.gguf " + "─" * max(0, 44 - len(quant)))
        test_base(quant, failures)

    # ── MrWhite cross-quant comparison ────────────────────────────────────────
    print("── MrWhite: quant comparison on flop raise spot " + "─" * 11)
    print("   fp16 and Q8_0 should raise; Q4_K_M may check under VRAM pressure.")
    print()
    from llama_cpp import Llama
    from inference_gguf import predict

    mrwhite_args = argparse.Namespace(
        blinds="$50/$100", stacks="$10,000",
        max_tokens=1, temperature=0.0, top_p=1.0,
        gpu_layers=-1, threads=None, ctx=512, verbose=False,
        lora_scale=1.0,
    )
    lora_path = ADAPTER_SUBDIR / "MrWhite.gguf"

    for quant in ["f16", "Q8_0", "Q4_K_M"]:
        base_gguf = GGUF_ADAPTER_DIR / f"base.{quant}.gguf"
        if not base_gguf.exists():
            print(f"  SKIP  base.{quant}.gguf not found")
            continue
        llm = Llama(
            model_path=str(base_gguf),
            lora_path=str(lora_path),
            lora_scale=1.0,
            n_ctx=512,
            n_gpu_layers=-1,
            verbose=False,
        )
        action = predict(llm, "MrWhite", FLOP_RAISE, mrwhite_args)
        llm.close()
        del llm
        action_is_raise = is_raise(action)
        if quant in ("Q8_0", "f16"):
            status = "OK" if action_is_raise else "FAIL"
            if not action_is_raise:
                failures[0] += 1
        else:
            # Q4_K_M may check after accumulated VRAM pressure — document, don't fail
            status = "OK" if action_is_raise else "NOTE"
        print(f"  {status}  MrWhite + {quant:<6} base → {action}")

    print()
    print("=" * 60)
    if failures[0] == 0:
        print("ALL TESTS PASSED")
    else:
        print(f"FAILURES: {failures[0]}")
    print("=" * 60)
    sys.exit(0 if failures[0] == 0 else 1)


if __name__ == "__main__":
    main()
